SELECT 
COD_UNICO CODIGO_UNICO, MONTO_EJEC, MONTO_VIABIL, NUM_PLAZO_EJEC, NUM_PLAZO_VIABIL, to_char(sysdate,'dd/mm/rrrr hh24:mi:ss') fecha_carga
FROM INV_DETALLE_CIERRE_EXPOST
WHERE COD_UNICO IS NOT NULL
AND (MONTO_EJEC IS NOT NULL AND MONTO_EJEC>=0)
AND (NUM_PLAZO_EJEC >= 0 OR NUM_PLAZO_EJEC IS NULL)
AND (NUM_PLAZO_VIABIL >= 0 OR NUM_PLAZO_VIABIL IS NULL)
AND (MONTO_VIABIL >= 0 OR MONTO_VIABIL IS NULL)
