SELECT COD_UNICO CODIGO_UNICO, TO_DATE(FEC_VIABIL,'DD/MM/RRRR') FEC_VIABIL, ID_CARTERA_INVERSION, ID_ESTADO, VAL_BENEFICIARIO_ULTIMO,
to_char(sysdate,'dd/mm/rrrr hh24:mi:ss') fecha_carga
FROM INV_PROYECTO
WHERE COD_UNICO IS NOT NULL
AND (ID_CARTERA_INVERSION >= 0 OR ID_CARTERA_INVERSION IS NULL)
AND ID_ESTADO IS NOT NULL
AND (VAL_BENEFICIARIO_ULTIMO >= 0 OR VAL_BENEFICIARIO_ULTIMO IS NULL)