SELECT ANO_EJE, CODIGO_UNICO, ESTADO_REG, FECHA_VALIDACION_BRECHA, TO_DATE(FECHA_VIABILIDAD,'DD/MM/RRRR') FECHA_VIABILIDAD, ID_BRECHA, ID_IDEA, NOMBRE_INVERSION, PIM, PROGRAMACION_INVERSION_ANIO0, PROGRAMACION_INVERSION_ANIO1, PROGRAMACION_INVERSION_ANIO2, PROGRAMACION_INVERSION_ANIO3, TIPO_NO_PREVISTA, VALIDACION_BRECHA, VERSION,
to_char(sysdate,'dd/mm/rrrr hh24:mi:ss') fecha_carga
FROM PRG_CARTERA_INVERSION
WHERE (ANO_EJE IS NULL OR ANO_EJE >=2005)
AND CODIGO_UNICO IS NOT NULL
AND ESTADO_REG IS NOT NULL
AND ESTADO_REG IN (0,1)
AND (PIM >=0 OR PIM IS NULL)
AND (PROGRAMACION_INVERSION_ANIO0>=0 OR PROGRAMACION_INVERSION_ANIO0 IS NULL)
AND (TIPO_NO_PREVISTA>=0 OR TIPO_NO_PREVISTA IS NULL)
AND VALIDACION_BRECHA IS NOT NULL
AND (VERSION IS NOT NULL AND VERSION>0)