SELECT ACT_PROY, ANO_EJE, MONTO_DEVENGADO, MONTO_PIM, TIPO_ACT_PROY, to_char(sysdate,'dd/mm/rrrr hh24:mi:ss') fecha_carga
FROM TR_PROY_ANO
WHERE ACT_PROY IS NOT NULL
AND (ANO_EJE IS NOT NULL AND ANO_EJE>=2004)
AND (MONTO_DEVENGADO IS NOT NULL AND MONTO_DEVENGADO>=0)
AND (MONTO_PIM IS NOT NULL AND MONTO_PIM>=0)
AND TIPO_ACT_PROY IS NOT NULL